### ISSUE TITLE
How to launch the shepherd tour programatically?

### ISSUE THREAD

**Issue by adamcoulombe** [shipshapecode/react-shepherd#29]
I see you can use the TourMethods to launch a tour by clicking a button how do I launch it, say, on component mount?

**Comment by adamcoulombe** [comment]
I tried 
```
class MyComponentContainer extends Component {
   render() {
      return (
         <TourMethods>
            {({ startTour }) => (

               <MyComponent startTour={startTour} {...this.props}>
                  {console.log(startTour)}   // logs undefined
               </MyComponent>
            )}
         </TourMethods>
      )
   }
}

class MyComponent extends Component {
componentDidMount(){
this.props.startTour()
}
   render() {
      return (
         ...
      )
   }
}

```

**Comment by rwwagner90** [comment]
@chuckcarpenter can you help figure this out? We should probably beef up our documentation as well.

**Comment by chuckcarpenter** [comment]
@adamcoulombe sorry about the delay, I can take a look at this tomorrow. Offhand, definitely appears to be a bug.

**Comment by chuckcarpenter** [comment]
@adamcoulombe not sure if anything has changed since you had this issue, but does it still show on latest release? I have this [branch](https://github.com/shipshapecode/react-shepherd/compare/issue/29) and was able to pass the prop as well as log it. In the example site I trigger the tour on mount as well:
![image](https://user-images.githubusercontent.com/706378/64052685-5ff2db00-cb34-11e9-879b-1a8b82646305.png)

**Comment by chuckcarpenter** [comment]
Assuming solved based on last comments.
