### ISSUE TITLE
can't have a multi-tour part with react history

### ISSUE THREAD

**Issue by MrWarzo** [shipshapecode/react-shepherd#636]
I have to use ```window.location.href``` if I wan't to change the current page but i can't use react history and i don't want to reload everytime the url change

**Comment by monshan** [comment]
Could you be more specific in describing your issue? Perhaps how to replicate?

On another note, `Shepherd` has recently been upgraded to version 10 and we have made the same dependency upgrade on `react-shepherd`. The update allows for step attachment on user event-triggered content or content that isn't shown until just before the step. Upgrading your `react-shepherd` version may solve the problem.

**Comment by dhhuynh2** [comment]
Just bumping this because I believe I have a similar problem. I think the issue described in the original post is that if you want to navigate to other pages via a certain step, in react, using react-router, you would either use the `useHistory` or `useNavigate` hooks. Because we're defining the logic in the steps array, you can't use hooks. You also can't use `window.location.href` because the page would reload and you would lose the tour I believe.

Is there a way to change page navigation from a shepherd step via react-router, then continue the tour?

**Comment by chuckcarpenter** [comment]
@dhhuynh2 wouldn't this work fine if you were just trying to update the URL? https://developer.mozilla.org/en-US/docs/Web/API/History/pushState
