### ISSUE TITLE
Intended install command causes errors

### ISSUE THREAD

**Issue by Necolanch** [shipshapecode/react-shepherd#638]
Running the install command listed in the README causes errors and can only be installed adding --force at the end of the command

**Comment by monshan** [comment]
Hello, you are experiencing this because your project is likely running `React 18` using `npm 7` and we have a peer dependency in the package for `React 17`. You have two options:

1. Use the `--legacy-peer-deps` option along with the install script to bypass the errors and install dependencies even with peer dependencies
2. Downgrade your project to `React 17` (the compatible version with the package)

This is driven by `npm 7`s default install of **peerDependencies**, if it suits you could also downgrade to `npm 6` to return to the default behavior of **NOT installing peerDependencies**.

**Comment by Nate-Wessel** [comment]
@monshan, so does `react-shephard` not work yet(?) with React 18? Is this in the works? I'm reluctant to use a global flag to get a single package working and I'm not likely to downgrade React for this.

**Comment by monshan** [comment]
@Nate-Wessel `react-shepherd` works with React 18, this issue has more to do with the distinction between how `npm 6` vs `npm 7+` handle peer dependencies and that react is a major dependency. Please reference the docs [here](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies)

**Comment by Nate-Wessel** [comment]
Thanks y'all!! Will this be released as a patch in 4.0.2?

**Comment by chuckcarpenter** [comment]
This has been released in v4.1.0
